include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # --- CONST (то что тебе нужно)
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # --- CLEAN CODE
    always_use_package_imports: true
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_this: true

    # --- FLUTTER STYLE
    sort_constructors_first: true
    use_key_in_widget_constructors: true

    # --- SAFETY
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    unnecessary_nullable_for_final_variable_declarations: true

    # --- READABILITY
    lines_longer_than_80_chars: false
    require_trailing_commas: true